### ISSUE TITLE
Update broccoli-filter

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/broccoli-lint-eslint#12]

**Comment by chriskrycho** [comment]
What needs doing here? I might be able to take a crack at it next week.

**Comment by jonathanKingston** [comment]
Dunno it's an API change and broccoli fixes take me way too much time to fathom :grin:

**Comment by chriskrycho** [comment]
Ha! I understand. I’ll take a look at the relevant details if I get a block of time in the next week; at the least I may be able to get a good handle on what needs to be done and write that up.

**Comment by rwjblue** [comment]
We likely need to be using broccoli-persistent-filter (to allow caching across builds).  A few reference examples (in a similar space):

* https://github.com/rwjblue/broccoli-jshint
* https://github.com/kellyselden/broccoli-jscs/
* https://github.com/sir-dunxalot/broccoli-sass-lint
* https://github.com/shinnn/broccoli-clean-css

**Comment by rwjblue** [comment]
Please let me know how I can help, I see getting this lib updated and released as a blocker for https://github.com/emberjs/rfcs/pull/119...

**Comment by chriskrycho** [comment]
I’ll take a gander on Monday and see what needs clarification, and see if I can get some cycles dedicated to it mid-week or so after some other, larger blockers are off my plate.

**Comment by rwjblue** [comment]
Also, I think we can avoid some pitfalls in those other libs by leveraging eslint's ability to access each files config and use that as a cache key (this makes the per file cache invalidation logic needed for broccoli-persistent-filter massively easier).

**Comment by rwjblue** [comment]
@chriskrycho - Awesome!  If you need/want to bounce things around ping me here, slack, twitter, whatever...

**Comment by chriskrycho** [comment]
@rwjblue: :+1: Will do!

**Comment by nickiaconis** [comment]
Oops didn't see this until now. I'm already working on this over at [nickiaconis/broccoli-eslinter/persistent-filter](https://github.com/nickiaconis/broccoli-eslinter/tree/persistent-filter), though it is to upgrade to broccoli-persistent-filter, which will help speed up builds.

**Comment by nickiaconis** [comment]
In the meantime, upgrading to the latest broccoli-filter should provide a solid basis for making the switch to broccoli-persistent-filter, so I opened PR #14 for that.

**Comment by chriskrycho** [comment]
Thanks for tackling it, @nickiaconis!

**Comment by nickiaconis** [comment]
A quick update for those watching here: #14, which updates broccoli-filter to a more recent version, has been merged. #21, which replaces it with broccoli-persistent-filter, is ready for review/merge.

**Comment by BrianSipple** [comment]
Closed by https://github.com/jonathanKingston/broccoli-lint-eslint/pull/21
