### ISSUE TITLE
Use of arrow functions breaks non-harmony node

### ISSUE THREAD

**Issue by samdoiron** [jonathanKingston/broccoli-lint-eslint#13]
lib/index.js, line 94 now uses an arrow function. This breaks node versions which do not support arrow functions (seemingly for a non-critical reason).

Edit: It seems that eb58bd8e77e3084bbe8926dda2703036d6b6fdea was to use ES6? Afaik, this still requires the `--harmony` flag with node, and this is causing syntax errors via `ember-cli-eslint ` for me. \

Edit2: This is because this change was a *minor version release*, despite breaking backwards compatibility, and because `ember-cli-eslint` depends on `^1.1.1`,

**Comment by jonathanKingston** [comment]
Yup the ideas is to compile with babel to ECMA5 using a prepublish, we should fix that immediately.

Sorry about that.

**Comment by samdoiron** [comment]
No problem, glad it's being looked into :+1:

**Comment by chriskrycho** [comment]
@jonathanKingston if you can hit this one, that'd be great. I've got a bunch of internal stuff to get back to knocking out today. :smile:

**Comment by cantsin** [comment]
Just hit this bug, thanks to @samdoiron for the clear description of what's happening. :+1:

**Comment by jonathanKingston** [comment]
@cantsin, @samdoiron or @chriskrycho could someone verify this is no longer happening with this branch:  https://github.com/jonathanKingston/broccoli-lint-eslint/tree/prebabelify-code

You might have to do some jiggery to get it to apply to a current ember project as npm at install time runs `npm prepublish`.

I'll then release this once verified, keen not to hurt more users.

Thanks all.

**Comment by samdoiron** [comment]
Ha, unfortunately I can't verify because it seems https://github.com/jonathanKingston/ember-cli-eslint has the same problem!

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by chriskrycho** [comment]
Worth note: an alternative solution is simply to add `"use strict";` in the relevant files, rather than going through the pre-babelify dance. Node is quite happy to deal with all the ES6 bits, as long as you're in strict mode.

**Comment by rwjblue** [comment]
@chriskrycho - That is true for node 0.12 but not node 0.10 (which ember-cli supports)

**Comment by chriskrycho** [comment]
Ah. We should file a bug on the downstream, then! (And I've stored it away mentally for reference.)

**Comment by brycekahle** [comment]
@jonathanKingston That branch does not work because `main` in `package.json` still points at `lib/index.js`. I presume it should be `build/index.js` instead?

**Comment by brycekahle** [comment]
@jonathanKingston Any update on a fix? This is currently blocking us because `ember-cli-eslint` has a dependency on this library of `^1.1.1`.

**Comment by jonathanKingston** [comment]
Someone pick up the helm from the branch I started on or you will likely be waiting two weeks.

**Comment by chriskrycho** [comment]
Seeing as this is a blocker for us, I'll probably be able to devote some time to it tomorrow. More then.

**Comment by chriskrycho** [comment]
@brycekahle Good catch; making that tweak seems to have done the trick. I'm testing further now; will submit a PR with that change and anything else I bump into in the next hour or so.

**Comment by chriskrycho** [comment]
No issues I see; any other testing against https://github.com/jonathanKingston/broccoli-lint-eslint/pull/19 would be welcome, but I think it's good to merge.
