### ISSUE TITLE
OS-dependent path-handling

### ISSUE THREAD

**Issue by chriskrycho** [jonathanKingston/broccoli-lint-eslint#15]
Some of the logic (e.g. [here]) depends on *nix-like paths, and therefore causes breakage on Windows.

I'm testing and putting together a pull-request now. If people are seeing breakages with the latest version of this or related packages on Windows, this is probably the reason.

[here]: https://github.com/jonathanKingston/broccoli-lint-eslint/blob/master/lib/index.js#L105

**Comment by joukevandermaas** [comment]
@jonathanKingston Do you think you can publish a new version to npm with #16 in? We'd like to use ESLint 2.0 on Windows.
