### ISSUE TITLE
Update versioning to match with 2.x eslint

### ISSUE THREAD

**Issue by bttf** [jonathanKingston/broccoli-lint-eslint#17]
Right now we're currently using the 1.1.1 version of broccoli-lint-eslint (via ember-cli-eslint), which pulls in eslint 1.x version

After a recent nombom, using 1.6.0 of broccoli-lint-eslint will pull in 2.x eslint, which breaks a bunch of stuff in our project (as it should since it is a major version change).

Wouldn't it make sense to have broccoli-lint-eslint's versioning change from 1.x to 2.x since it includes a breaking change (2.x eslint)?

**Comment by rwjblue** [comment]
Yes, I think the major change of a primary dep should be a major bump here too.

**Comment by jonathanKingston** [comment]
Somewhat disagree with mandatory bumping as the bigger issue is default configs and also how the code was written for the latest release.

It's been bumped now anyhow, sorry for the disruption.

**Comment by rwjblue** [comment]
@jonathanKingston - Ya, I agree it isn't mandatory, but eslint@1.x to eslint@2.x seems like it might be a breaking change (regardless of this library at all)...
