### ISSUE TITLE
Other maintainer wanted

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/broccoli-lint-eslint#20]
I haven't used Ember for the last 8 or so months, which means that I'm taking a lot of my free time to manage changes on projects like this.

I would like a keen maintainer who can work in times when I am busy.

Apply here.

**Comment by rwjblue** [comment]
Happy to take over...

**Comment by jonathanKingston** [comment]
I am pretty sure you are alpha blue right now. Connected to the matrix. :D @rwjblue 

Happy to get involved with discussions etc but my focus isn't on the latest broccoli changes etc to know.

In fact I was hoping there would be some form of way to pass this onto the community more so. Perhaps a set github organisation for popular but slightly underepresented addons?
