### ISSUE TITLE
Latest version is missing `build` directory when installed

### ISSUE THREAD

**Issue by BrianSipple** [jonathanKingston/broccoli-lint-eslint#22]
I'm playing around with to using `broccoli-lint-eslint` @ 2.0.0 inside of ember-cli-eslint, and the installed package only includes these:

CHANGELOG.md
LICENSE
README.md
conf/
lib/
node_modules/
package.json

This causes `require('broccoli-lint-eslint')` to fail with a "module not found" error, as `main` in `package.json` is pointing to `build/index.js`. It looks like there's a prepublish hook in our `package.json` that should be in charge of creating `build`, so I'm not yet sure what the cause might be.

**Comment by BrianSipple** [comment]
Update: I might be wrong, but I think that having `build` in `.gitignore` is keeping from being included in the published package. I can submit a quick PR for a fix if this is the case.

**Comment by rwjblue** [comment]
I do not think that the `.gitignore` itself is the issue (though that is definitely a good line of thinking), we specify specific files to include in the package ([see here](https://github.com/jonathanKingston/broccoli-lint-eslint/blob/master/package.json#L29-L31)) and that doesn't include `build`.

As an example project with a similar goal, take a look at tildeio/htmlbars:

* `dist/` is ignored in `.gitignore` -- https://github.com/tildeio/htmlbars/blob/master/.gitignore#L1
* `files` in `package.json` specifically includes `dist/` -- https://github.com/tildeio/htmlbars/blob/master/package.json#L22-L26

See: 

* https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
* https://docs.npmjs.com/files/package.json#files

**Comment by rwjblue** [comment]
A PR would be most welcome to add `build` to the `files` array in `package.json`.
