### ISSUE TITLE
Pin ESLint dependency to 2.2.0

### ISSUE THREAD

**Issue by BrianSipple** [jonathanKingston/broccoli-lint-eslint#23]
There's a [current issue with ESLint @2.3.0](https://github.com/babel/babel-eslint/issues/267) that seems to be causing a lot of problems in consuming libraries using it alongside `babel-eslint`. 

I mentioned it on an [`eslint-config-ember` issue a few weeks ago](https://github.com/jonathanKingston/eslint-config-ember/issues/6), but I didn't quite realize the extent of what it would affect. In short -- even after trying to hack together custom dependencies locally -- `ember-cli-eslint` currently seems to be unusable due to deeper dependencies such as `broccoli-lint-eslint` using `eslint-2.3.0`. 

After digging in to `ember-cli-eslint`, `eslint-config-ember`, `eslint-config-nightmare-mode` and `broccoli-lint-eslint`, I'd like to propose a path forward that includes pinning everything using eslint to `eslint`@2.2.0 until there's a resolution to the issue above -- or until we can jump ahead to ESLint 2.4.0 (which seems to be where a lot of the chatter is `babel-eslint` is leaning). 

If this sounds reasonable, I'd certainly be willing to help out with pulling some of the strings that that might require.

**Comment by rwjblue** [comment]
Sounds like a good plan, I've followed that issue and we can unpin when it is fixed. 

Would you mind submitting a PR to lock us to `eslint@2.2.2` as suggested in the issue?

**Comment by rwjblue** [comment]
I think the latest babel-eslint@6 beta will solve this issue, and prevent having to pin the dep.  Can you test it?

**Comment by chriskrycho** [comment]
@rwjblue, I've tested locally and confirmed, and included that in https://github.com/jonathanKingston/ember-cli-eslint/pull/39. That's still blocked by https://github.com/jonathanKingston/eslint-config-ember/pull/7, however.

**Comment by BrianSipple** [comment]
@chriskrycho So, if I'm understanding the current status of everything, there's a PR to upgrade `eslint-config-ember` to `eslint`@ 2.4.0, and then have `ember-cli-eslint` play off of that -- in conjunction with `ember-cli-eslint` itself using `babel-eslint` @ 6.0.0-beta.6. 

Your above comment suggests that this gets us past the  babel-eslint and estraverse-fb issue from `eslint` @ 2.3.0 / babel-eslint 5, but your comment in [jonathanKingston/ember-cli-eslint#39](https://github.com/jonathanKingston/ember-cli-eslint/pull/39) mentions that this isn't the case. 

Maybe I'm misreading one or the other -- in either case, it looks like our first priority is getting `eslint-config-ember` to the version that our [`ember-cli-eslint` PRs](https://github.com/jonathanKingston/ember-cli-eslint/pull/39) [are expecting](https://github.com/jonathanKingston/ember-cli-eslint/pull/40).

**Comment by chriskrycho** [comment]
@BrianSipple great points of needed clarification.

1. Good catch on the status of babel-eslint in https://github.com/jonathanKingston/ember-cli-eslint/pull/39 – I forgot to update the PR description after adding that change. It's correct now, and the estraverse-fb problem should be resolved.
2. I think your summary is correct; we want to merge eslint-config-ember, then our PRs 39 and 40 on ember-cli-eslint update this to reference the new version of that dependency.
3. To resolve *this* issue, I think we should be able to jump ahead to babel-eslint 2.4.0 and proceed. I'm happy to help wrangle all of that tomorrow afternoon or Wednesday.
