### ISSUE TITLE
Needs to have 2.2.0 published to NPM

### ISSUE THREAD

**Issue by BrianSipple** [jonathanKingston/broccoli-lint-eslint#32]
@jonathanKingston I recently bumped the package version after merging [the recent changes that were pegged to the milestone](https://github.com/jonathanKingston/broccoli-lint-eslint/milestones) and drafted a new release, but I don't appear to have NPM publishing perms at the moment. I didn't realize that -- so apologies for getting too far ahead with the bump -- but perhaps a quick publish could be made to keep everything in sync.

**Comment by jonathanKingston** [comment]
Hey! I added you a while back under this account: https://www.npmjs.com/~briansipple
I can push the changes if you prefer?

**Comment by BrianSipple** [comment]
Ah, the username I mainly use is actually `bsipple`. If you'd like to initiate the publish, though, by all means, feel free.

**Comment by BrianSipple** [comment]
I went ahead and published after logging in with `briansipple`. If it wouldn't be too much trouble, though, @jonathanKingston, could I ask to be added under `bsipple`. I actually had no idea that the former account existed until now 😄 .

**Comment by rwjblue** [comment]
@BrianSipple you can do that yourself when logged in as briansipple: `npm owner add bsipple`

**Comment by BrianSipple** [comment]
@rwjblue Excellent point 😄
