### ISSUE TITLE
Support for ".eslintrc.js"

### ISSUE THREAD

**Issue by Turbo87** [jonathanKingston/broccoli-lint-eslint#33]
ESLint has lately introduced support for using an `.eslintrc.js` file among [other formats](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) which adds the ability to include comments into the files. Would it be possible to add support for those files to the plugin too?

**Comment by rwjblue** [comment]
I believe this should already be working, can someone test?

**Comment by BrianSipple** [comment]
I've just been reading up on https://github.com/jonathanKingston/ember-cli-eslint/pull/53 and love what having this work here would enable. 

@rwjblue I haven't tried yet, but I'll be able to dig in to this a bit more later today and I can check then. In either case, I might also like to add something to the test suite that explicitly makes sure this is covered.

**Comment by Turbo87** [comment]
I just tested this with `ember-cli-eslint@1.3.0` and indeed it seems to work without any issues!
